### ISSUE TITLE
Le pictogramme du Dôme reste affiché

### ISSUE THREAD

**Issue by misterppqx** [Le-Dome-RDS/generateur-graphique-open-badge#4]
Bonjour,
Le picto du Dôme par défaut reste affiché après avoir choisi un autre picto.
![image](https://user-images.githubusercontent.com/5037420/150553556-e285a192-b89c-46bb-8d9b-9b1dd1c014ad.png)
Peux-tu jeter un coup d'oeil ?
Merci

**Comment by tmaziere** [comment]
Bonjour @misterppqx 

Est-ce que ça se produit systématiquement, ou dans une configuration particulière ?
Dans quel format est le picto personnalisé ? Je veux bien que tu me le fasses passer pour mes tests.

**Comment by misterppqx** [comment]
En effet, pas à chaque fois. Peu importe le picto, disponible ou importé en png. C'est en changeant la couleur que ça arrive.
Teste ce badge http://openbadges.ledome.info/generateur/customize/index.html?id=pc2
Ajoute un picto et change la couleur
![image](https://user-images.githubusercontent.com/5037420/150557071-8dd8ba69-ae79-41f2-94c9-7e79dccdbac7.png)

**Comment by tmaziere** [comment]
Visiblement c'est un défaut du modèle, je vais regarder ça avec @norgut-morgut !

**Comment by norgut-morgut** [comment]
Je viens de faire un test, et effectivement, avec le badge "Parcours" de Niveau 2 "Je suis engagé", le logo du Dôme réapparait après avoir changé la couleur fond et filet "posture". par contre ce n'est pas le cas avec celui de niveau 1 et de niveau 3. je n'ai pas testé les autres. @tmaziere, je vais regarder pour celui de niveau 2 pourrait réagir comme ça.

**Comment by norgut-morgut** [comment]
@tmaziere, j'ai trouvé d'où venez le bug. Dans le fichier du modèle "Pc2.svg", le logo du "O" du Dôme était présent 2 fois ,l'un sur l'autre. J'en ai donc supprimé 1. @misterppqx, vous pouvez tester à nouveau ce modèle. Normalement le bug a disparu. Par contre, il faudra vider le cache de votre ordinateur pour que la correction soit pris en compte.

**Comment by misterppqx** [comment]
@norgut-morgut Merci.
Test validé.
Bug fermé.
