### ISSUE TITLE
Faute de frappe à corriger

### ISSUE THREAD

**Issue by misterppqx** [Le-Dome-RDS/generateur-graphique-open-badge#5]
Ligne 90
https://github.com/Le-Dome-RDS/generateur-graphique-open-badge/blob/main/src/decisionTree.json

   {"id": 430, "title": "ou savoir auxquels ont a été initié", "level": 1, "childOf": 400, "badgeId": "Sv2"},

**Changer ont par on**
Merci

**Comment by tmaziere** [comment]
@norgut-morgut est-ce que tu peux prévoir ça ?

**Comment by tmaziere** [comment]
C'est corrigé.

Pour info la branche qui correspond à http://openbadges.ledome.info/generateur/ est `https://github.com/Le-Dome-RDS/generateur-graphique-open-badge/tree/subdirectory-setup`.
