### ISSUE TITLE
Overlap du png sur un visuel

### ISSUE THREAD

**Issue by misterppqx** [Le-Dome-RDS/generateur-graphique-open-badge#6]
Bonjour,
On a un overlap sur ce visuel
http://openbadges.ledome.info/generateur/customize/index.html?id=pc2
![image](https://user-images.githubusercontent.com/5037420/225975914-1a4d120f-10c4-49c9-b30d-03f87e673ade.png)
Merci

**Comment by tmaziere** [comment]
Bonjour @misterppqx 

~~Je ne reproduis pas le soucis, peux tu joindre ton fichier image (le visuel à insérer) et m'indiquer comment tu procèdes ?~~

Je vois le problème, je regarde.

**Comment by tmaziere** [comment]
@misterppqx 

C'est corrigé, merci de me confirmer que c'est OK.
(Penser à vider le cache)

(poke @norgut-morgut )

**Comment by misterppqx** [comment]
You can close the issue. Thks
